default: &default
  adapter: cockroachdb
  host: <%= Rails.application.credentials.dig(:cockroachdb, :host) %>
  port: 26257
  user: <%= Rails.application.credentials.dig(:cockroachdb, :user) %>
  password: <%= Rails.application.credentials.dig(:cockroachdb, :password) %>
  database: <%= Rails.application.credentials.dig(:cockroachdb, :database) %>
  sslmode: "verify-full"
  sslrootcert: "./root.crt"
  options: <%= Rails.application.credentials.dig(:cockroachdb, :option) %>

development:
  <<: *default
  database: social_media_api_development

test:
  <<: *default
  database: social_media_api_test

production:
  <<: *default
